### ISSUE TITLE
[FIX] "Unable to find any packages" on the website for a brief time

### ISSUE THREAD

**Issue by oganexon** [nestdotland/nest.land#105]
**Describe the bug**
It's a low priority bug.
When loading the gallery, for a brief period of time the message "Unable to find any packages" appear even if packages are found.

**To Reproduce**
https://nest.land/gallery

**Expected behavior**
"Loading packages" message should stay longer

**Screenshots**
![nest](https://user-images.githubusercontent.com/52361520/85201276-7144e800-b2fe-11ea-86ea-e6d918acd9b6.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - nest.land Version [e.g. 0.1.0]

**Smartphone (please complete the following information):**
 - OS: Windows & Android
 - Browser Chrome & Firefox
 - nest.land Version 0.1.3

**Comment by tbaumer22** [comment]
This issue occurs because of the way I wrote the gallery loading order. I'll see if I can find a solution to this. I wrote this code in the middle of the night, so hopefully I'll be able to think clearer!
