### ISSUE TITLE
[FEATURE] Copy module URL when clicked

### ISSUE THREAD

**Issue by oganexon** [nestdotland/nest.land#106]
**Is your feature request related to a problem? If so, please describe.**
Again, a low priority feature.
I'd like to be able to click on the URL and have it copied into my clipboard.

**Describe the solution you'd like**
- just as soon as we click on the URL
- or a button next to the URL to copy the string

**Describe alternatives you've considered**
N/A

**Comment by tbaumer22** [comment]
This would be very useful. I'll add it to my todo list.
