### ISSUE TITLE
Remove No README warning when there is a REAMDME.md

### ISSUE THREAD

**Issue by Yamboy1** [nestdotland/nest.land#118]
**Is your feature request related to a problem? If so, please describe.**
When i ran eggs publish, it said `No README found at project root`, although I do have a README.md, this should probably be covered

**Describe the solution you'd like**
README.md autodetection supported as well as just README

**Describe alternatives you've considered**
N/A

**Additional context**
GitHub's default readme file is also README.md

**Comment by oganexon** [comment]
@Yamboy1 on which version of eggs are you? This problem was fixed after v0.1

**Comment by Yamboy1** [comment]
![image](https://user-images.githubusercontent.com/37413895/85275262-31cff480-b4d4-11ea-8520-cdafd90f8475.png)
 I'm on v0.1.2, what version do i need?

**Comment by zorbyte** [comment]
This is false, we do not support any other files except ones ending with the .md extension. We should fix this.

**Comment by oganexon** [comment]
I'm sorry if I misunderstood the issue
But you said README.md is undetected? That shouldn't happen

**Comment by zorbyte** [comment]
Behaviour is also reflected by website it seems. https://i.reupload.gg/T7W8A0WMR.png

**Comment by MartonDev** [comment]
I remember this happening with me too, but it uploaded the README anyways, it just logged that no REAME was found. Try adding it to the files field manually, if you use globalization, like this:
```
"files": [

    "./src/**/*",
    "./README.md"

  ]
```

**Comment by Yamboy1** [comment]
Yeah, it did work on the website, so I assume it was just an error in the warning

**Comment by Yamboy1** [comment]
Updated title

**Comment by oganexon** [comment]
Can you show us the structure of your directory so we can reproduce the error?

**Comment by MartonDev** [comment]
@oganexon We just need to update the readme check. Right now it's only checking if there is a readme in the `files` field. 
It says "No readme found" if there is a readme, but it's not in the egg.json

**Comment by oganexon** [comment]
Okay, I didn't understand the problem like that 😉 
So the readme should be published in any case

**Comment by MartonDev** [comment]
Working on this rn
