### ISSUE TITLE
Community-maintained modules

### ISSUE THREAD

**Issue by MartonDev** [nestdotland/nest.land#121]
**Is your feature request related to a problem? If so, please describe.**
Currently Nest.land lacks major package support. It is still in development, so that's perfectly fine, but in order to gain users, the project just needs to have the essential/most popular packages for Deno

**Describe the solution you'd like**
This is the point when *Community-maintained* packages come in. All Nest.land users will be able to upload packages they don't own, but want to see on Nest.land. 

A field would be added to the config file, named `communityPackage`, defaulting to false. If a user wants to publish a package that they don't hold the copyright/license to, they will need to set this to true, and link the original source/location of the module in an another field called `copyrightSource`.

Once published, the package would be available from an *irregular* url, like this: `https://x.nest.land/@community/Houston@1.0.0/mod.ts` or `https://x.nest.land/community@Houston@1.0.0/mod.ts` (comment suggestions below, the point is to distinguish the package from regular packages *in the url*.) 
The website would also indicate if a package is community-maintained in the package's information panel/card and also in an element at the top of the package preview, with links to the original source/location of the module. 
A documentation section would be also created where users could read more about community-maintained packages (and original copyright holders would be granted with a link where they can request a removal).

**Development branch for this issue is available [here](https://github.com/MartonDev/nest.land/tree/community-packages-dev).**

**Comment by MartonDev** [comment]
Screenshots:
![ss1](https://user-images.githubusercontent.com/30638105/85301860-ad1bb100-b4a8-11ea-88b0-c5260f256936.png)
![ss2](https://user-images.githubusercontent.com/30638105/85301862-adb44780-b4a8-11ea-8b6a-874e7abc768f.png)

**Comment by oganexon** [comment]
That's a great idea.
We just need to think about how to limit abuse and especially prevent the publication of false versions with potentially viruses and malware.

**Comment by MartonDev** [comment]
For this, the best solution would probably be, that these type of packages would require manual review after the user requested a publish.

**Comment by tbaumer22** [comment]
Perhaps there would be a way to scan the corresponding repository for this package and compare the files of a given branch? This way, if the files don't exactly match what is in source control, we know that they have tampered with the package.

**Comment by MartonDev** [comment]
But what if they publish an older version?

**Comment by tbaumer22** [comment]
We could compare by release version?

**Comment by MartonDev** [comment]
Hmm...
We'll definitely have to write a clear documentation for this feature

**Comment by tbaumer22** [comment]
@zorbyte I'd love to hear your opinion on this. The more that I think about it, the more appealing it seems. We'll just have to figure out an innovative and secure way to implement it.

**Comment by zorbyte** [comment]
What if the original owner wishes to upload their package? How can we verify beyond doubt that the user claims to be who they say they are?

**Comment by MartonDev** [comment]
That is partially why we have the repository field. It will be mandatory for community packages and will contain the original repo.

**Comment by zorbyte** [comment]
Closed due to ethical, legal and malware concerns.
