### ISSUE TITLE
[FEATURE] Pressing enter to fetch the API key

### ISSUE THREAD

**Issue by yg** [nestdotland/nest.land#166]
**Is your feature request related to a problem? If so, please describe.**

It would be great if we press enter to fetch the API key instead of mouse click

**Describe the solution you'd like**

Pressing enter to fetch the API key

**Additional context**

![Screenshot](https://user-images.githubusercontent.com/61746440/85999748-3e030700-ba2a-11ea-991b-4efac5e6d1f6.png)

**Comment by divy-work** [comment]
This won't be hard to implement. Can be done in routine PRs.
