### ISSUE TITLE
[CHORE] Meet criteria for Vercel Sponsorship

### ISSUE THREAD

**Issue by tbaumer22** [nestdotland/nest.land#182]
Nest.land is attempting to be sponsored by Vercel, but needs to meet the following criteria before we are eligible:

- [x] The project should be open-source.
- [x] The project should be static rather than server-rendered.
- [ ] A Vercel banner in the footer of each site page.
- [ ] A Vercel banner in the source repository's `README.md` file.
- [ ] All links back to Vercel should use a UTM tag with the format: `?utm_source=[project-name]`.

For more information, visit [this](https://vercel.com/knowledge/can-vercel-sponsor-my-project) link.

**Comment by MartonDev** [comment]
I'll work on the Vercel banner stuff. As for the links, I'm not sure what changes that requires

**Comment by tbaumer22** [comment]
Sounds good @MartonDev. Feel free to check out @maximousblk's design for the new footer and see if that would work.
