### ISSUE TITLE
[BUG] Website says module should be imported from mod.ts, when the entry file is set to mod.js

### ISSUE THREAD

**Issue by TheWizardBear** [nestdotland/nest.land#185]
**Description**

The description at https://nest.land/package/maze_generator says that the package can be used with ...`mod.ts`:
![modts](https://user-images.githubusercontent.com/42446683/86374756-d4c70200-bc7c-11ea-8e39-8a505eff3e80.png)

even though the egg.json file says ...`mod.js` (and using the URL stated doesn't work):
![eggjson](https://user-images.githubusercontent.com/42446683/86374737-cf69b780-bc7c-11ea-9595-ce73f00a3a05.png)

**Expected behavior**
It should display exactly the same except with a `.js` at the end of the URL instead of `.ts`.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox 78
 - nest.land Version 0.1.2

**Comment by MartonDev** [comment]
We will be working on adapting the entry field in the front end in the near future

**Comment by MartonDev** [comment]
Actually might just do it today
