### ISSUE TITLE
Case sensitive package urls

### ISSUE THREAD

**Issue by t8** [nestdotland/nest.land#195]
**Describe the bug**
We have a normalized name field built in to our API, but the site does not utilize this feature for navigating to packages.

**To Reproduce**
Try to visit: https://nest.land/package/Nessie
And then try to visit: https://nest.land/package/nessie

**Expected behavior**
The link for [nessie](https://nest.land/package/nessie) should work along with the link for [Nessie](https://nest.land/package/Nessie)

**Desktop (please complete the following information):**
 - OS: macOS
 - nest.land Version 0.1.8

CC @justablob

**Comment by jletey** [comment]
@tbaumer22 Maybe we should just use the normalised package names for the urls?

**Comment by halvardssm** [comment]
Hi! Just wondering if it is possible to change my package url? I much rather have `https://nest.land/package/nessie` than `https://nest.land/package/Nessie` 😄

**Comment by maximousblk** [comment]
Unfortunately it's not possible to change the package url. When working on the [rewrite](https://github.com/nestdotland/roadmap/issues), we'll keep this issue in mind and rewrite all capitalizations to the normalized version.
