### ISSUE TITLE
[BUG] Images with realtive file paths don't work in a markdown file on the nest.land website

### ISSUE THREAD

**Issue by TheWizardBear** [nestdotland/nest.land#208]
## Describe the bug
Images with realtive file paths don't work in a markdown file on the nest.land website.

## To Reproduce

[Here](https://nest.land/package/maze_generator), there should be an image of a maze, but it isn't loading correctly.
`![Kruskal's maze](images/Kruskals-20x20.png)`

## Expected behavior
It should show an image, like it does [here](https://deno.land/x/maze_generator), on deno.land/x.

It works for absolute URLs, like in the [deno_gui README](https://nest.land/package/deno_gui)

### Currently looks like this:
![image not loading (deno.land/x)](https://user-images.githubusercontent.com/42446683/87286908-575b8700-c4f1-11ea-801a-9517df6dbf94.png)

### Should look more like this:

![image loading properly (nest.land/package)](https://user-images.githubusercontent.com/42446683/87286974-722dfb80-c4f1-11ea-9e88-70b8570b67df.png)

**Comment by MartonDev** [comment]
Thanks for reporting, I shall work on this

**Comment by MartonDev** [comment]
By the way, you don't have your images directory uploaded to nest.land. You should upload it, relative paths won't work otherwise. 
![image](https://user-images.githubusercontent.com/30638105/87294948-c5f61000-c504-11ea-8e18-8202e5f899af.png)
I just recoded our relative path resolver, so now everything should be working after the pull request

**Comment by TheWizardBear** [comment]
@MartonDev Thank you!

> By the way, you don't have your images directory uploaded to nest.land. You should upload it, relative paths won't work otherwise.

Oh, I didn't notice that. :/
I have some other folders that aren't there too.
I think it's because I tried to add all of the files with:
```
"files": [
    "*"
  ]
```
but I didn't realize that that doesn't include folders.
