### ISSUE TITLE
Add alternative Arweave import urls to the site

### ISSUE THREAD

**Issue by t8** [nestdotland/nest.land#232]
**Describe the solution you'd like**
Introducing direct Arweave urls would give users a direct line of contact with the blockweave that hosts module data. Even if x.nest.land were to have an outage, this gateway would not go down. 

Theoretically, even if it did, we'd easily be able to 1) spin up our own gateway or 2) use the same exact transaction string in the url with another gateway such as `perma.online`.

**Additional context**
This would remove a developer's ability to see analytics from a direct Arweave import url, but this is a tradeoff that the end user should have the decision of making. 

The Arweave transaction strings are already within the API; we just have to display them on the site in a clever way that does not impede on the UX.

Note: X will have the ability to record analytics.

**Comment by zorbyte** [comment]
Not a good first issue tate :)

**Comment by martonlederer** [comment]
Closing this, integrated in #276
