### ISSUE TITLE
No README? Then say it.

### ISSUE THREAD

**Issue by littledivy** [nestdotland/nest.land#244]
Upload a module with no README and stare 10 mins at this:
![image](https://user-images.githubusercontent.com/34997667/88659145-3484c180-d0f2-11ea-9702-25f34dc7e327.png)

**Comment by t8** [comment]
Haha fair point. This is something that should be addressed.

**Comment by michael-spengler** [comment]
Proposal: `eggs publish` should already fail, if no README.md is included.

If you guys agree, let's move this to https://github.com/nestdotland/eggs --> I would like to try implementing this.

**Comment by oganexon** [comment]
@michael-spengler We try as much as possible to move away from any established standard. 
For example in the next version the eggs.json configuration file will no longer be mandatory. 

There is already a warning in the CLI if the readme is not found. While this may seem like a critical part of any module, but I don't think a readme should be made mandatory. 
Indeed, one can imagine that some authors might want to write all their documentation in the source files and use tools like `deno doc` to see the docs

**Comment by martonlederer** [comment]
@littledivy what module did you use, that has no readme? Gonna work on this, but I don't have anything to test with

**Comment by oganexon** [comment]
@martonlederer Try this module https://nest.land/package/delete_me/files
And then we'll remove this module from the gallery

**Comment by martonlederer** [comment]
Thanks
