### ISSUE TITLE
[FEATURE] Forward to Arweave Transaction

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/nest.land#255]
User Story:
As a user of https://nest.land/ - I want to navigate to the Arweave Transaction when I click ... "Published on" ... (see screenshot) - in order to get infos about the transaction. 

![Screen Shot 2020-09-09 at 6 44 03 PM](https://user-images.githubusercontent.com/43786652/92628340-f374f500-f2cc-11ea-99c1-4bebc3213b78.png)

**Comment by t8** [comment]
@michael-spengler Moved this to the nest.land repo, as it pertains to the frontend. 

If you'd like to work on this, feel free! I think it would be a very neat feature.

**Comment by michael-spengler** [comment]
@t8 Thanks :) this makes sense. 

I'll check it in the evening. Coming from the ABAP GUI and later Angular world this is an appropriate first vue challenge for me. 👍

**Comment by michael-spengler** [comment]
The plan: 
Navigate to https://viewblock.io/ ...  e.g. 

https://viewblock.io/arweave/tx/Zh-J83lpDobVxA9U85KYM_L4y1A-L_xoub76PcdmRuM 

--> user can e.g. click on "Show Encoded Data" there + e.g. find out transaction id of a json file which is helpful when accessing raw JSON data per https request - e.g. https://arweave.net/tx/PQ5YVI6bfAifozCnIGwx38sCbwDxkiwzKCq0cRg0Q1I/data.json

**Comment by t8** [comment]
Awesome! That will be a great addition.

I came from Angular before as well. Personally, I am a much bigger fan of Vue than Angular now.

**Comment by michael-spengler** [comment]
Implemented by PR: https://github.com/nestdotland/nest.land/pull/256
