### ISSUE TITLE
idea: target="_blank" for links from gallery? 

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/nest.land#258]
I just browsed through some modules from the gallery and thought it might be good to open them in a new tab. IMO this would improve the browsing / exploration experience. Please correct me if I'm wrong on this. If some of you confirm this, I would implement this.

**Comment by michael-spengler** [comment]
![Screen Shot 2020-09-11 at 10 28 04 PM](https://user-images.githubusercontent.com/43786652/92969910-1692d680-f47e-11ea-9738-ee4349577255.png)

prerequisite: #262

**Comment by t8** [comment]
Interesting idea. In most cases, I'm against redirecting to a new tab. Perhaps a better UX would be adding a back button, similar to what we do for all of the `std` modules?

See: https://nest.land/std/_util/0.68.0

![image](https://user-images.githubusercontent.com/20846869/92970043-082bc700-f44c-11ea-96df-6b4297cf16f0.png)

**Comment by michael-spengler** [comment]
good idea
