### ISSUE TITLE
Regarding: Featured Modules

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/nest.land#259]
1. Would it be good to reveal the mechanism which is behind selecting specific modules as featured modules within the docs?
2. Would it be an improvement to have a link underneath (see screenshot) called - "[Browse Gallery](https://nest.land/gallery)" 

![Screen Shot 2020-09-11 at 9 49 06 PM](https://user-images.githubusercontent.com/43786652/92967139-03c9d300-f479-11ea-907d-b73dca4ab8e8.png)

**Comment by martonlederer** [comment]
The featured modules are [randomly selected](https://github.com/nestdotland/nest.land/blob/master/src/components/home/FeaturedPackages.vue#L40) from the 20 last updated modules, we could mention this in the docs, but anyone can check the code.
I'm not sure about another button/link. I think it would ruin the clean look of the featured modules, and there's already the menu at the top.

**Comment by t8** [comment]
To preserve minimalism, it may be best to leave that page as is. We could consider adding information about the mechanism behind it to the docs, but I doubt people would look in the docs for that type of information...
