### ISSUE TITLE
Minor UI Improvement - see screenshot

### ISSUE THREAD

**Issue by michael-spengler** [nestdotland/nest.land#260]
Instead of 

![Screen Shot 2020-09-11 at 9 59 48 PM](https://user-images.githubusercontent.com/43786652/92967899-535cce80-f47a-11ea-8a7b-170a3c67b20f.png)

it should imo look like

![Screen Shot 2020-09-11 at 9 59 35 PM](https://user-images.githubusercontent.com/43786652/92967921-61125400-f47a-11ea-94d5-f0e94b0cb3e8.png)

PR is underway.

**Comment by t8** [comment]
Great catch! Didn't notice this before. Thanks!
