### ISSUE TITLE
LICENSE file not loading after refreshing the page.

### ISSUE THREAD

**Issue by Yamboy1** [nestdotland/nest.land#304]
I came across a bug earlier today in which, after navigating to a LICENSE file in nest.land package, it fails to load after refreshing the page. I found this error in the console:
![image](https://user-images.githubusercontent.com/37413895/100527516-077b2380-3238-11eb-91a2-fedb571439bc.png)
Here's a screencast showing how to reproduce the issue:
https://drive.google.com/file/d/1oQCk6nRBlWQgXhukrWXWWpvicHHp_fjB/view

Let me know if you need more information!

**Comment by maximousblk** [comment]
looks like same as #298
