### ISSUE TITLE
moudle publish sucess，unable to access

### ISSUE THREAD

**Issue by BubbleM** [nestdotland/nest.land#307]
https://nest.land/package/umajs_deno

![image](https://user-images.githubusercontent.com/15670955/105001077-280e6f80-5a6a-11eb-8c13-057367f6ad9e.png)

**Comment by maximousblk** [comment]
context: [api/package/umajs_deno](https://x.nest.land/api/package/umajs_deno)

was `1.0.0` published after `2.0.0`?

**Comment by oganexon** [comment]
Looks like it
https://github.com/nestdotland/nest.land/discussions/306

**Comment by BubbleM** [comment]
> context: [api/package/umajs_deno](https://x.nest.land/api/package/umajs_deno)
> 
> was `1.0.0` published after `2.0.0`?
> 
> this is a issue can be fixed in the front end. the module is published properly and the imports will work.

yes ，When I first released it, I mistakenly released 2.0.0
Is there any way to fix it or change the package name

**Comment by maximousblk** [comment]
there's no way to change the package name. you'll have to publish it with a new name.

**Comment by maximousblk** [comment]
@BubbleM try it now on https://nest-land-git-fix-607.nestdotland.vercel.app

**Comment by BubbleM** [comment]
> @BubbleM try it now on https://nest-land-git-fix-607.nestdotland.vercel.app

ok thx
