### ISSUE TITLE
api routes doesn't work in localhost ?

### ISSUE THREAD

**Issue by moncefplastin07** [nestdotland/nest.land#317]
i try to serve nest.land on my localhost Everything is working fine but when I try to extract the bulbul I get the following error ``Error: Request failed with status code 404
``

![image](https://user-images.githubusercontent.com/26319214/122063832-86a50300-cde8-11eb-9628-6d220d49eab9.png)

**Comment by maximousblk** [comment]
you need to use the vercel cli: https://vercel.com/docs/cli

- fork the repo
- connect the fork to your vercel account
- clone the fork (and and run `npm i`)
- install the vercel cli (`npm i -g vercel`)
- run `vc` or `vercel` in the repo
- run `vc dev` or `vercel dev` in the repo
