### ISSUE TITLE
MVP 2 - Major refactors

### ISSUE THREAD

**Issue by zorbyte** [nestdotland/nest.land#45]
MVP 2's design focus will be for the standardisation of technologies, modularity and service segregation.

Key Concepts and/or Goals:
  - [ ] Package CDN:
     - Support Vanilla JS with TypeScript Definitions through the `X-TypeScript-Types` 
       header
  - [ ] API:
     - Dockerise this, setup automatic deployments to server through GitHub actions
     - Allow custom READMEs. This applies to both a custom name and location
  - [ ] Common Module:
     - Types, such as request payloads and DB data shapes. `common/types`
     - The import follower. `common/follower`
     - API library for web and possibly server side if required. `common/api`
  - [ ] Style Guide
     - Enforce branch naming system:
       - Create a regex for GitHub branch naming rules
       - For long term features, quick fixes or bug fixes use the following format:
         - Use feature branches named as: `feature/<feature_name>`
         - Use bug fix branches named as `fix/<fix_name>`
       - Use `master` for production deployments
       - Use a trunk branch, probably named `in-dev`
     - Enforce commit naming guidelines. See [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
     - Enforce a file naming scheme
     - Create an eslint configuration
     - Use a common prettier config that is compatible with `deno fmt`
     - Follow the [Deno style guide](https://github.com/denoland/deno/blob/4ebd24342368adbb99582b87dc6c4b8cb6f44c87/docs/contributing/style_guide.md) where applicable
  - [ ] Website:
     - Allow users to browse the file tree of a module
     - Allow users to view a user profile along with all their packages
     - Relative files in READMEs should be fixed
     - Gallery should display the eggs CLI first, followed by packages ordered by using 
       the popularity of it multiplied by a randomness factor which becomes larger the 
       less popular the packages are to allow them to compete (hopefully to be mixed 
       with big packages and just below them). The favouritism feature for small 
       packages should only be enabled when its versions and usages/requests of each 
       version breaks a relatively small but reasonable threshold. This would avoid 
       random "nonsense" packages from appearing at the top as well as provide incentive 
       for package developers to market their packages
     - Rewrite website in TypeScript
     - Use the API library from the common modules

**Comment by fakoua** [comment]
I would suggest adding Category for a package (categories and keywords)

**Comment by tbaumer22** [comment]
@fakoua this is an interesting idea. What would some examples of categories be?

**Comment by fakoua** [comment]
@tbaumer22 categories could be: Web Framework, Command lines, utilities, string manipulation, User Interface, Images, Console, ...
And keywords comma separated.

**Comment by tbaumer22** [comment]
@fakoua we'll look into adding this feature sometime in the future. It should definitely help with navigation through the packages!

**Comment by zorbyte** [comment]
Closing due to major changes that conflict with this issue.
