### ISSUE TITLE
[BUG] Installation URL not accurate for any file other than mod.ts

### ISSUE THREAD

**Issue by tbaumer22** [nestdotland/nest.land#67]
**Describe the bug**
If a user were to use an "index" file other than `mod.ts`, the registry would not update this information.

**To Reproduce**
Publish a package to the registry that does not use `mod.ts` as the main script in the project root.

**Expected behavior**
The index file should be passed through the API to allow the frontend to fetch and set it dynamically.

**Screenshots**
![image](https://user-images.githubusercontent.com/20846869/84585247-d159fc80-addb-11ea-99af-42cfec6c9793.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - nest.land Version: 0.1.0

**Additional context**
Blob is assigned to this as well because it involves the API.

**Comment by zorbyte** [comment]
This issue is likely related to this. https://github.com/nestlandofficial/nest.land/pull/68/files#diff-158ea6b3ac0cffb5f82d6b92e71bdaa8R328-R330

**Comment by justablob** [comment]
I'd say we should make a mod.ts file mandatory, as it seems to already be a standard in the Deno community.

**Comment by zorbyte** [comment]
It's a de facto standard. We shouldn't.

**Comment by divy-work** [comment]
It's not an official standard though, this should be considered as it might drive away people who have their project working with another index file, they would not want to change it.

**Comment by zorbyte** [comment]
Why is this marked as in valid?

**Comment by tbaumer22** [comment]
My apologies. I marked this issue as invalid because the website was showing invalid information. I must have misunderstood the meaning of this tag.

**Comment by tbaumer22** [comment]
We've implemented an `"entry"` file for `0.1.3`, but this is not added in the frontend yet. This addition will be coming soon!
