### ISSUE TITLE
[FEATURE] Scope permissions for eggs CLI installation

### ISSUE THREAD

**Issue by asos-craigmorten** [nestdotland/nest.land#89]
**Is your feature request related to a problem? If so, please describe.**

Both the GitHub readme and https://nest.land website suggest installation with a command similar to:

```bash
deno install -A -f --unstable -n eggs https://x.nest.land/eggs@0.1.0/mod.ts
```

The use of the heavily permissive `-A` "allow all" flag is somewhat unsettling (though tbh at least it is called out with Deno, in Node we wouldn't even be asked!)

**Describe the solution you'd like**

I can appreciate that it is certainly shorter and easier to use the command with the `-A` flag, so I don't want to suggest you remove it necessarily.

Perhaps just add somewhere to the readme and / or website a "long version" of the command which details the exact and minimal permissions required so users can make use of Deno's security sandboxing feature if they desire to.

**Describe alternatives you've considered**

Certainly expansion on the project diagram to document flows of the CLI would be insightful as to the required permissions and their uses (e.g. making network request to API, writing and reading the auth key to / from the dot file).

**Additional context**

Onboarding [Opine](https://github.com/asos-craigmorten/opine/pull/12) and trying to get into the security first mindset that Deno now allows us to have 😄 

P.S. very cool idea - keep up the nice work!

**Comment by tbaumer22** [comment]
This is a great idea. Though I'm almost positive that `eggs` requires all permissions, we can definitely write up some documentation as to why these permissions are necessary.

**Comment by oganexon** [comment]
**Detailed permissions:**
* init
  * __--allow-write__: write to the egg config file 
  * __--allow-read__: read previous config
* install
  * __--allow-write__: write to the .eggs-global-modules.json config file 
  * __--allow-read__: read previous config
  * __--allow-net__: get latest module version
  * __--allow-run__: install module
  * __--allow-env__: get home dir
* link
  * __--allow-write__: write to the .nest-api-key config file 
  * __--allow-env__: get home dir
* publish
  * __--allow-read__: read egg config file
  * __--allow-net__: fetch module data & publish module
* update
  * __--allow-write__: write to the dependencies file 
  * __--allow-read__: read dependencies file 
  * __--allow-net__: get the latest module version
  * __--allow-env__: get global config file for executables
  * __--allow-run__: update executables
* upgrade
  * __--allow-net__: get the latest eggs version
  * __--allow-run__: upgrade eggs

**Comment by tbaumer22** [comment]
@oganexon thanks so much for listing these! I'll make additions to our CLI README with this list soon. This is extremely helpful!

**Comment by t8** [comment]
@asos-craigmorten, Marton has added this list of necessary permissions to the new documentation. Until the new PR is merged, feel free to view the permissions here: https://docs.nest.land/installation.html#permissions-used

Thanks again for mentioning this!

**Comment by jsejcksn** [comment]
@t8 I propose that the nest.land API functionality of `eggs` be split into a separate exported module that can be used exclusively with [scoped permissions](https://deno.land/manual/getting_started/permissions#permissions-allow-list). (ref. https://github.com/nestdotland/nest.land/issues/170#issue-647844339). Users can then create higher-level abstractions for providing the necessary permission arguments while retaining sandbox control of their own environments. Just handing over the keys is not something that everyone can do.

**Comment by t8** [comment]
@jsejcksn are you referring to building a sort of Deno API client for nest.land?

This would be possible, and not too difficult to do. You raise a good point about giving away permissions.

**Comment by jsejcksn** [comment]
> are you referring to building a sort of Deno API client for nest.land?

Exactly. And `eggs` would be the dogfood consumer

**Comment by t8** [comment]
I really like this idea. Once we fully convert to our Rust API, I think that this would be a great focus.

Side note: I think that we're straying away from the topic of this issue. I'm going to leave this linked to #200, and you are more than welcome to make a feature request!
